### ISSUE TITLE
Dicas gerais para a sequência do projeto

### ISSUE THREAD

**Issue by viniagostini** [gabrielguim/scheduler-api#1]
Ei Gabriel, beleza?

Dei uma olhada no seu projeto e ele tá muito bem estruturado!

Umas dicas para o andamento do projeto:

1) Adicione a descrição do seu projeto no README.md, isso ajuda as pessoas que irão acompanhar seu projeto a entender o que você está fazendo.

2) Não deixe pra testar tudo no final. Vai ser muito chato e provavelmente isso vai influenciar negativamente na qualidade dos testes.

Abraços

**Comment by gabrielguim** [comment]
Passei uma semana viajando e por isso não tive progresso nos ultimos dias e nem atualizei o README.

Mas valeu pelo feedback e lembrança! 👌
